server:
  # 后端服务运行端口号
  port: 8088
  tomcat:
    max-swallow-size: 20MB

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis-plus:
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  typeAliasesPackage: com.lcx.domain
logging:
  level:
    com.lcx: debug
    org.springframework.ai: debug

# Redis配置(已放入application-dev.yml)
# MySQL配置(已放入application-dev.yml)
# 文件存储配置(已放入application-dev.yml)
# Token配置(已放入application-dev.yml)